version: "3.7"

services:
  mongodb_container:
    image: mongo:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: prisma-mongo
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network

  app_container:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: secret
    ports:
      - "3000:3000"
    depends_on:
      - mongodb_container
    networks:
      - app-network

volumes:
  mongodb_data_container:

networks:
  app-network:
    driver: bridge
